name: CI

on:
  push:
    branches:
      - dev
      - temp

jobs:
  build:
    name: 1.Build & Test Jar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Swap environment variables
        working-directory: ./src/main/resources
        run: |
          echo "${{ secrets.AUTH_PROD_YML }}" >> ./auth.yml
          echo "${{ secrets.ENV_PROD_YML }}" >> ./env.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" >> ./application-prod.yml

      # https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - name: gradle dependency caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Docker compose
        run: |
          export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}  
          docker compose up -d

      - name: Wait for mysql
        run: |
          docker ps
          while ! docker exec carrot_mysql mysql --user=root --password=${{ secrets.MYSQL_ROOT_PASSWORD }} -e "SELECT 1" >/dev/null 2>&1;
          do
              sleep 2
              echo "waiting for mysql.."
          done

      - name: Test with Gradle
        run: MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} ./gradlew build
